import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from "../components/home/header/ThemeToggle";
import { ThemeProvider } from "../components/ThemeProvider/ThemeProvider";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Intelligent Personal Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeProvider>
            {children}
            <div className="absolute top-6 right-5">
              <ThemeToggle />
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
