import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Intelligent Personal Feed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen w-full bg-[#020617] relative">
          <div
            className="absolute inset-0 z-0"
            style={{
              background: "#020617",
              backgroundImage: `
                linear-gradient(to right, rgba(59,130,246,0.12) 1px, transparent 1px),
                linear-gradient(to bottom, rgba(99,102,241,0.12) 1px, transparent 1px),
                radial-gradient(circle at 50% 60%, rgba(59,130,246,0.25) 0%, rgba(99,102,241,0.15) 40%, rgba(139,92,246,0.05) 70%)
              `,
              backgroundSize: "40px 40px, 40px 40px, 100% 100%",
            }}
          />

          <div className="relative z-10 text-white">{children}</div>
        </div>
      </body>
    </html>
  );
}
